                default:
                    if(c!=' ')
                    {
                        if(ispressed[lctrl]||ispressed[rctrl])
                        {
                            if(c=='l')
                            {
                                clear();
                                prompt();
                                printf("%s",buffer[buffer_current]);
                                return;
                            }
                        }
                        if(ispressed[lshift]||ispressed[rshift])
                        {
                            c=shift_charcode[keycode];
                        }
                        if(buffer_index<BUFFER_SIZE)
                        {
                            buffer[buffer_current][buffer_index++]=c;
                            printf("%c",c);
                        }
                    }
                    break;
            }
